<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">บันทึกรายจ่าย&nbsp;[&nbsp;<?= $recordID; ?>&nbsp;]</h4>
                <p class="card-category">(รายการและเอกสาร)</p>
            </div>
            <div class="card-body">
                <!-- begin of form -->
                <form id="demo1" method="post">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <!--<label for="exampleFormControlSelect1">ใช้ในโครงการ</label>-->
                                <div class="bootstrap-select form-control">
                                    <select class="form-control selectpicker" data-style="btn btn-link"
                                            data-live-search="true" id="exampleFormControlSelect1" tabindex="-98">
                                        <option value="">ใช้ในงาน/โครงการ</option>
                                        <option value="99999">อื่นๆ</option>
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">ผู้ซื้อ</label>
                                <input type="text" class="form-control" value="">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">วันที่ซื้อ</label>
                                <input type="text" class="form-control datetimepicker2"
                                       id="id4_input_buydate" name="PAY_DATE"
                                       value="">
                            </div>
                        </div>
                        <!--
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">จำนวนเงิน (ตามบิล)</label>
                                <input type="text"
                                       class="form-control number-separator text-danger"
                                       autofocus/>
                            </div>
                        </div>
                        -->
                    </div>

                    <!-- row of supplier -->
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">ซื้อจาก</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Tax-ID</label>
                                <input type="text" class="form-control" max="13"
                                       pattern="[0-9]{13}"/>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">สาขา</label>
                                <input type="text" class="form-control" max="5"/>
                            </div>
                        </div>
                    </div>
                    <!-- row of supplier -->

                    <!-- 2 rows of supplier's address -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">ที่อยู่ (เลขที่, หมู่บ้าน,
                                    อาคาร)</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">ตำบล/แขวง</label>
                                <input name="district" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">อำเภอ/เขต</label>
                                <input name="amphoe" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">จังหวัด</label>
                                <input name="province" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">รหัสไปรษณีย์</label>
                                <input name="zipcode" type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                    <!-- 2 rows of supplier's address -->

                    <!-- row of file(s) evidence -->
                    <!--
                    <div class="row">
                        <div class="col-md-12">
                            <div class="bd-example" data-example-id="">
                                <div class="form-group form-file-upload form-file-multiple">
                                    <input type="file" multiple="" class="inputFileHidden">
                                    <div class="input-group">
                                        <input type="text" class="form-control inputFileVisible"
                                               placeholder="Multiple Files" multiple>
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-fab btn-round btn-primary"
                                                    data-toggle="tooltip" data-placement="bottom" title="ไฟล์เอกสาร"><i
                                                        class="material-icons">attach_file</i></button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    -->

                    <!-- test upload -->
                    <?php $project_refnumber = '111'; ?>
                    <div class="row">
                        <div class="col-md-12 border-bottom">
                            <div class="form-group" id="id4_div_file_<?= $project_refnumber; ?>">
                                <!--<label for="id4_input_file_projectFile">สำเนาสัญญา/สำเนาโครงการ</label><br>-->
                                <label class="btn btn-primary btn-fab btn-round" data-toggle="tooltip"
                                       data-placement="bottom" title="ไฟล์เอกสาร"
                                       id="id4_button_file_<?= $project_refnumber; ?>"><i class="material-icons">attach_file</i><input
                                            type="file"
                                            multiple
                                            style="display:none;"
                                            name="proj_file_<?= $project_refnumber; ?>"
                                            id="id4_input_file_<?= $project_refnumber; ?>"
                                            onchange="updateFiles2Upload('<?= $project_refnumber; ?>', 'bill_paid', 'expenses.phtml?refNumber2Edit=<?= $project_refnumber; ?>')"/>
                                </label><span
                                        id="id4_span4_file_<?= $project_refnumber; ?>"><?= chkFileExist($project_refnumber, "." . DIRECTORY_SEPARATOR . "bill_paid"); ?></span>
                            </div>
                        </div>
                    </div>
                    <!-- row of file(s) evidence -->

                    <!-- row of expense details -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <!--<label>รายละเอียดรายจ่าย</label>-->
                                <div class="form-group">
                                    <label class="bmd-label-placeholder"> อธิบายรายละเอียดการจ่าย </label>
                                    <textarea class="form-control" rows="5"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- row of expense details -->

                    <!-- row of save button -->
                    <div class="row d-flex justify-content-end mr-0">
                        <button type="submit" name="submit" value="xxx"
                                class="btn btn-primary btn-round pull-right"> บันทึก
                        </button>
                    </div>
                    <!--<div class="clearfix"></div>-->
                    <!-- row of save button -->
                </form>
                <!-- end of form -->
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">โครงการ</h4>
                <p class="card-category">(งานหรือโครงการ)</p>
            </div>
            <div class="card-body">
                <form>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="bmd-label-floating">ชื่อโครงการ</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="bmd-label-floating">ลูกค้า</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label class="bmd-label-floating">โครงการเริ่ม</label>
                                <input type="text" class="form-control datetimepicker2"
                                       id="id4_input_date_prjstart" name="PRJ_DATESTART"
                                       value="">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label class="bmd-label-floating">โครงการปิด</label>
                                <input type="text" class="form-control datetimepicker2"
                                       id="id4_input_date_prjstop" name="PRJ_DATESTOP"
                                       value="">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <!--<label for="exampleFormControlSelect1">ประเภทโครงการ</label>-->
                                <div class="bootstrap-select form-control">
                                    <select class="form-control selectpicker" data-style="btn btn-link"
                                            data-live-search="true" id="exampleFormControlSelect1"
                                            tabindex="-98">
                                        <option value="">เลือกประเภทโครงการ</option>
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <span data-toggle="modal" data-target="#exampleModal">
                             <!--class="btn btn-primary btn-fab btn-fab-mini btn-round mb-2"-->
                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="เพิ่มประเภทโครงการ"><button
                                            type="button" class="btn btn-sm btn-fab btn-round btn-primary mt-4"><i
                                                class="material-icons">add</i></button></a>
                            </span>
                        </div>
                    </div>
                    <div class="row mt-0">
                        <div class="col-md-12">
                            <div class="form-group">
                                <!--<label>รายละเอียดโครงการ</label>-->
                                <div class="form-group">
                                    <label class="bmd-label-placeholder"> อธิบายรายละเอียดโครงการ </label>
                                    <textarea class="form-control" rows="5"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row d-flex justify-content-end mr-0">
                        <button type="submit" class="btn btn-primary btn-round pull-right">บันทึก</button>
                    </div>
                    <!--<div class="clearfix"></div>-->
                </form>
            </div>
        </div>
    </div>
    <!--<div class="col-md-4">
        <div class="card card-profile">
            <div class="card-avatar">
                <a href="javascript:;">
                    <img class="img" src="../theme-bs4/material-backend/assets/img/faces/marc.jpg" />
                </a>
            </div>
            <div class="card-body">
                <h6 class="card-category text-gray">CEO / Co-Founder</h6>
                <h4 class="card-title">Alec Thompson</h4>
                <p class="card-description">
                    Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                </p>
                <a href="javascript:;" class="btn btn-primary btn-round">Follow</a>
            </div>
        </div>
    </div>-->
</div>

<!-- Card show existing data -->
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">Simple Table</h4>
                <p class="card-category"> Here is a subtitle for this table</p>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class=" text-primary">
                        <th>
                            ID
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Country
                        </th>
                        <th>
                            City
                        </th>
                        <th>
                            Salary
                        </th>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                1
                            </td>
                            <td>
                                Dakota Rice
                            </td>
                            <td>
                                Niger
                            </td>
                            <td>
                                Oud-Turnhout
                            </td>
                            <td class="text-primary">
                                $36,738
                            </td>
                        </tr>
                        <tr>
                            <td>
                                2
                            </td>
                            <td>
                                Minerva Hooper
                            </td>
                            <td>
                                Curaçao
                            </td>
                            <td>
                                Sinaai-Waas
                            </td>
                            <td class="text-primary">
                                $23,789
                            </td>
                        </tr>
                        <tr>
                            <td>
                                3
                            </td>
                            <td>
                                Sage Rodriguez
                            </td>
                            <td>
                                Netherlands
                            </td>
                            <td>
                                Baileux
                            </td>
                            <td class="text-primary">
                                $56,142
                            </td>
                        </tr>
                        <tr>
                            <td>
                                4
                            </td>
                            <td>
                                Philip Chaney
                            </td>
                            <td>
                                Korea, South
                            </td>
                            <td>
                                Overland Park
                            </td>
                            <td class="text-primary">
                                $38,735
                            </td>
                        </tr>
                        <tr>
                            <td>
                                5
                            </td>
                            <td>
                                Doris Greene
                            </td>
                            <td>
                                Malawi
                            </td>
                            <td>
                                Feldkirchen in Kärnten
                            </td>
                            <td class="text-primary">
                                $63,542
                            </td>
                        </tr>
                        <tr>
                            <td>
                                6
                            </td>
                            <td>
                                Mason Porter
                            </td>
                            <td>
                                Chile
                            </td>
                            <td>
                                Gloucester
                            </td>
                            <td class="text-primary">
                                $78,615
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="" method="post">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">เพิ่มประเภทโครงการ</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-8 offset-2">
                            <div class="form-group">
                                <label class="bmd-label-floating">ประเภทโครงการใหม่</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark btn-round btn-sm" data-dismiss="modal">ปิด
                    </button>
                    <button type="submit" class="btn btn-primary btn-round btn-sm">บันทึก</button>
                </div>


            </form>
        </div>
    </div>
</div>